# docker build -t magdielmarques/codeeducation:latest -f Dockerfile.single . 
# docker run --rm -it --name golang  magdielmarques/codeeducation  
FROM golang:1.8 AS builder

WORKDIR $gopath/hello

COPY hello.go . 

RUN go build -o hello.go .

EXPOSE 3000

CMD ./hello.go
