# docker build -t magdielmarques/codeeducation:latest -f Dockerfile.multistage . 
# docker run --rm -it --name golang  magdielmarques/codeeducation  

# stage 1
FROM golang:1.8 AS builder

WORKDIR $gopath/hello

COPY hello.go . 

RUN go build -o hello.go .

## stage 2
FROM alpine:latest  

WORKDIR /app

COPY --from=builder $gopath/hello/hello.go .

EXPOSE 3000

CMD ./hello.go